[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
JumpProcesses = "ccbc3e58-028d-4f4c-8cd5-9ae44345cda5"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PiecewiseDeterministicMarkovProcesses = "86206cdf-4603-54e0-bd58-22a2dcbf57aa"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Synapse = "7cc9ea39-daa9-4846-be95-d8a08c9e3c85"

[compat]
BenchmarkTools = "1.3.2"
JumpProcesses = "9.7.3"
OrdinaryDiffEq = "6.55.0"
PiecewiseDeterministicMarkovProcesses = "0.0.7, 0.0.8"
Plots = "1.39.0"
Synapse = "0.0.1"
